print("  SRI GOODWILL COMPUTERS"  )
Print(" ____________________________________")
print("  The Institute of Computers and accounts")
print("  ___________________________________________________")
print(" Address:2-257-2,Society Colony,NTR Circle,MADANAPALLE-517325")
print("phone no:08571-224222, whatsapp no:9959993974")
print("_____________________________________________________")
print("               Reciept ")
print("                     Date:3-7-2025.   ")
print("Name of the student:K.NIKHIL REDDY.")
print("Course:C language. Batch no:1108. Timings:11am-1pm")
print(" SI NO.       PARTICULARS           AMOUNT")
Print("1.            Course fees           10,000")
print("2.            Registration fees           ")
print("3.            Eamination Fees             ")
print("4.            Tally prime exam fees       ")
print("5.            Books/Others.               \n")
print(" Due Amount__________                Total:10,000")
print("Due to be paid on date_________\n")
print(" Rupees in Words:TEN THOUSAND RUPEES ONLY")
print(" \n x K.NIKHIL REDDY")
print(" Student/Guardian signature")
print(" Fees once paid shall not be refunded")